{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- .Values.config.data | nindent 4 }}
{{- end }}
