apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.rootless .Values.podAnnotations }}
      annotations:
        {{- if .Values.rootless }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
        container.seccomp.security.alpha.kubernetes.io/{{ .Chart.Name }}: unconfined
        {{- end }}
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "buildkit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.rootless | ternary "master-rootless" (default .Chart.AppVersion .Values.image.tag) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --addr
            - unix:///run/{{ .Values.rootless | ternary "user/1000" ""}}/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          {{- if .Values.rootless }}
            - --oci-worker-no-process-sandbox
          {{- end }}
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
          {{- if .Values.rootless }}
            runAsUser: 1000
            runAsGroup: 1000
          {{- else }}
            privileged: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
