apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.rootless .Values.podAnnotations }}
      annotations:
        {{- if .Values.rootless }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
        {{- end }}
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "buildkit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "buildkit.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.rootless .Values.tls.enabled .Values.buildkitdToml }}
          volumeMounts:
          {{- if .Values.buildkitdToml }}
            - name: config
              mountPath: {{ if .Values.rootless }}/home/user/.config/buildkit{{ else }}/etc/buildkit{{ end }}
          {{- end }}
          {{- if .Values.tls.enabled }}
            - name: certs
              readOnly: true
              mountPath: /certs
          {{- end }}
          {{- if .Values.rootless }}
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
          {{- end }}
          {{- end }}
          args:
            - --addr
            - unix:///run/{{ .Values.rootless | ternary "user/1000" ""}}/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          {{- if .Values.rootless }}
            - --oci-worker-no-process-sandbox
          {{- end }}
          {{- if .Values.tls.enabled }}
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
          {{- end }}
          {{- if .Values.debugLog }}
            - --debug
          {{- end }}
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
          {{- if .Values.rootless }}
            seccompProfile: # Needs Kubernetes >= 1.19
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          {{- else }}
            privileged: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.rootless .Values.tls.enabled .Values.buildkitdToml }}
      volumes:
      {{- if .Values.buildkitdToml }}
      - name: config
        configMap:
          name: buildkitd-config
      {{- end }}
      {{- if .Values.rootless }}
      - name: buildkitd
        emptyDir: {}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: certs
        secret:
          secretName: {{ include "buildkit.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
