changelog:
  categories:
    - title: '🐳 Buildkit Service'
      labels:
        - 'buildkit-service'
    - title: '🚬 Smocker Mock server'
      labels:
        - 'smocker'
    - title: '🚀 New Features'
      labels:
        - 'feature'
    - title: '🔬 Improvements'
      labels:
        - 'improvement'
    - title: '🐞 Bug Fixes'
      labels:
        - 'bug'
    - title: '📦 Dependency updates'
      labels:
        - 'dependencies'
    - title: '📄 Documentation updates'
      labels:
        - 'documentation'
    - title: '🛠️ Maintenance'
      labels:
        - 'chore'
