# required value for dependabot-gitlab deployment
credentials:
  gitlab_access_token: token
  maven:
    private:
      url: test-url
      username: username
      password: password

mongodb:
  auth:
    username: username
    password: password

redis:
  master:
    persistence:
      enabled: false

image:
  repository: registry.gitlab.com/dependabot-gitlab/dependabot
  tag: master-latest

web:
  startupProbe:
    initialDelaySeconds: 30

worker:
  startupProbe:
    initialDelaySeconds: 30

projects:
  - test-repo

env:
  gitlab_url: gitlab.testing.svc.cluster.local
