# required value for dependabot-gitlab deployment
credentials:
  gitlab_access_token: token

registriesCredentials:
  DOCKERHUB_TOKEN: token
  NPMJS_TOKEN: token

redis:
  master:
    persistence:
      enabled: false

projects:
  - test-repo

env:
  gitlabUrl: http://gitlab.testing.svc.cluster.local:4567
