# required value for dependabot-gitlab deployment
credentials:
  gitlab_access_token: token

mongodb:
  auth:
    username: username
    password: password

image:
  repository: registry.gitlab.com/dependabot-gitlab/dependabot
  tag: check-sidekiq-latest

web:
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false

worker:
  startupProbe:
    enabled: false
  livenessProbe:
    enabled: false
