# required value for dependabot-gitlab deployment
credentials:
  gitlab_access_token: token

mongodb:
  enabled: true
  auth:
    enabled: true
    username: username
    password: password

image:
  repository: registry.gitlab.com/dependabot-gitlab/dependabot
  tag: master-latest
