# required value for dependabot-gitlab deployment
credentials:
  gitlab_access_token: token

mongodb:
  auth:
    username: username
    password: password

redis:
  master:
    persistence:
      enabled: false

image:
  repository: registry.gitlab.com/dependabot-gitlab/dependabot
  tag: check-sidekiq-latest

web:
  startupProbe:
    initialDelaySeconds: 30

worker:
  startupProbe:
    initialDelaySeconds: 30
