image:
  # -- Image to use for deploying
  repository: docker.io/andrcuns/dependabot-gitlab
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: ""

# -- Override chart name
nameOverride: ""
# -- Override fully qualified app name
fullnameOverride: ""

serviceAccount:
  # -- Create service account
  create: false
  # -- Service account annotations
  annotations: {}
  # -- Service account name
  name: ""

service:
  # -- Service type
  type: ClusterIP
  # -- Service pot
  port: 3000
  # -- Service annotations
  annotations: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

# -- Pod annotations
podAnnotations: {}

# -- Node selectors
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}

# -- Security Context
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

web:
  # -- Web container replicas count
  replicaCount: 1
  # -- Web container resource definitions
  resources: {}
  livenessProbe:
    # -- Enable liveness probe
    enabled: true
    # -- Liveness probe failure thresold
    failureThreshold: 5
    # -- Liveness probe period
    periodSeconds: 10
    # -- Liveness probe timeout
    timeoutSeconds: 1
  startupProbe:
    # -- Enable startup probe
    enabled: true
    # -- Startup probe initial delay
    initialDelaySeconds: 10
    # -- Startup probe failure threshold
    failureThreshold: 12
    # -- Startup probe period
    periodSeconds: 10
    # -- Startup probe timeout
    timeoutSeconds: 3

worker:
  # -- Worker container replicas count
  replicaCount: 1
  # -- Worker container resource definitions
  resources: {}
  livenessProbe:
    # -- Enable liveness probe
    enabled: true
    # -- Liveness probe failure threshold
    failureThreshold: 2
    # -- Liveness probe period
    periodSeconds: 120
    # -- Liveness probe timeout
    timeoutSeconds: 3
  startupProbe:
    # -- Enable startup probe
    enabled: true
    # -- Startup probe initial delay
    initialDelaySeconds: 10
    # -- Startup probe failure threshold
    failureThreshold: 12
    # -- Startup probe period
    periodSeconds: 5
    # -- Startup probe timeout
    timeoutSeconds: 3

createProjectsJob:
  # -- Job Backoff Limit
  backoffLimit: 2
  # -- Job Active Deadline
  activeDeadlineSeconds: 30

migrationJob:
  # -- Job Backoff Limit
  backoffLimit: 4
  # -- Job Active Deadline
  activeDeadlineSeconds: 60

env:
  # -- Redis URL
  redisUrl: ""
  # -- MongoDB URL
  mongoDbUrl: ""
  # -- Gitlab instance URL
  gitlabUrl: https://gitlab.com
  # -- Optional sentry dsn for error reporting
  sentryDsn: ""
  # -- Optional app url, used for automated webhook creation
  dependabotUrl: ""
  # -- Configuration path
  appConfigPath: kube/config
  # -- App root
  appRootPath: /home/dependabot/app
  # -- Dependabot comment command prefix
  commandsPrefix: ""
  # -- Update job retry count or 'false' to disable
  updateRetry: 2
  # -- Enable metrics endpoint for prometheus
  metrics: true

credentials:
  # -- Gitlab access token, required
  gitlab_access_token: ""
  # -- Github access token
  github_access_token: ""
  # -- Gitlab auth token for webhook authentication
  gitlab_auth_token: ""

# -- Credentials for private registries:
# PRIVATE_DOCKERHUB_TOKEN: token
registriesCredentials: {}

project_registration:
  # -- Project registration mode
  mode: "manual"
  # -- Cron expression of project registration cron job
  cron: ""
  # -- Allowed namespace expression for projects to register
  namespace: ""

# -- List of projects to create/update on deployment
projects: []

# ref: https://github.com/bitnami/charts/tree/master/bitnami/redis
redis:
  # -- Enable redis installation
  enabled: true
  # -- Redis architecture. Allowed values: `standalone` or `replication`
  architecture: standalone
  # -- Override redis name
  fullnameOverride: redis
  # -- Kubernetes Cluster Domain
  clusterDomain: cluster.local
  auth:
    # -- Enable authentication
    enabled: true
    # -- Redis password
    password: "redis-password"

# ref: https://github.com/bitnami/charts/tree/master/bitnami/mongodb
mongodb:
  # -- Enable mongodb installation
  enabled: true
  # -- String to fully override mongodb.fullname template
  fullnameOverride: mongodb
  # -- Kubernetes Cluster Domain
  clusterDomain: cluster.local
  auth:
    # -- Enable authentication
    enabled: true
    # -- MongoDB root password
    rootPassword: ""
    # -- MongoDB custom user username
    username: "dependabot-gitlab"
    # -- MongoDB custom user password
    password: "mongodb-password"
    # -- MongoDB custom database
    database: dependabot_gitab
  service:
    # -- Mongodb service port
    port: 27017
