name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*
      - .github/**/*
  push:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*
      - .github/**/*

env:
  KUBECONFORM_VERSION: "0.4.14"
  HELMDOCS_VERSION: "1.5.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.3.1
      - name: Lint
        run: ct lint --config .github/config/ct-lint.yaml --check-version-increment=false
      - name: Lint docs
        run: .github/script/helm-docs.sh

  kubeconform:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run kubeconform
        run: .github/script/kubeconform.sh

  install:
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeconform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.3.1
      - name: Check changes
        id: changes
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        if: steps.changes.outputs.changed == 'true'
        uses: helm/kind-action@v1.4.0
      - name: Install
        if: steps.changes.outputs.changed == 'true'
        run: ct install --config .github/config/ct-install.yaml
