name: Workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*
      - .github/**/*
  push:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*

env:
  KUBEVAL_VERSION: "0.15.0"
  HELMDOCS_VERSION: "1.4.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/ct-lint.yaml
      - name: Lint docs
        if: steps.lint.outputs.changed == 'true'
        run: .github/script/helm-docs.sh

  kubeval:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check changes
        id: changes
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: list-changed
      - name: Run kubeval
        if: steps.changes.outputs.changed == 'true'
        run: .github/script/kubeval.sh

  install:
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeval
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check changes
        id: changes
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: list-changed
      - name: Create kind cluster
        if: steps.changes.outputs.changed == 'true'
        uses: helm/kind-action@v1.0.0
      - name: Install
        if: steps.changes.outputs.changed == 'true'
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/ct-install.yaml

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeval
      - install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
