name: Workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*
      - .github/**/*
  push:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*

env:
  KUBEVAL_VERSION: "0.15.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: .github/ct.yaml

  kubeval:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache kubeval
        uses: actions/cache@v2
        with:
          path: kubeval
          key: ${{ runner.os }}-kubeval-${{ env.KUBEVAL_VERSION }}
      - name: Run kubeval
        run: script/kubeval.sh

  install:
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeval
    strategy:
      matrix:
        k8s:
          - v1.16.15
          - v1.17.11
          - v1.18.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check changes
        id: changes
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: list-changed
      - name: Create kind ${{ matrix.k8s }} cluster
        if: steps.changes.outputs.changed == 'true'
        uses: helm/kind-action@v1.0.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Install
        if: steps.changes.outputs.changed == 'true'
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: install
          config: .github/ct.yaml

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - lint
      - kubeval
      - install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
