name: Workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*
      - .github/**/*
  push:
    branches:
      - master
    paths:
      - charts/**/*
      - script/**/*

env:
  KUBEVAL_VERSION: "0.15.0"
  HELMDOCS_VERSION: "1.4.0"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Lint
        run: ct lint --config .github/ct-lint.yaml
      - name: Lint docs
        run: .github/script/helm-docs.sh

  kubeval:
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Run kubeval
        run: .github/script/kubeval.sh

  install:
    runs-on: ubuntu-20.04
    needs:
      - lint
      - kubeval
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Check changes
        id: changes
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Create kind cluster
        if: steps.changes.outputs.changed == 'true'
        uses: helm/kind-action@v1.1.0
      - name: Deploy fake gitlab
        if: steps.changes.outputs.changed == 'true'
        run: |
          kubectl create namespace testing
          kubectl apply -f charts/dependabot-gitlab/ci/fake-gitlab.yaml -n testing
      - name: Install
        if: steps.changes.outputs.changed == 'true'
        run: ct install --config .github/ct-install.yaml

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    needs:
      - lint
      - kubeval
      - install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1.1
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
