name: Release

on:
  push:
    branches:
      - master
    paths:
      - charts/*/Chart.yaml

env:
  KUBEVAL_VERSION: "0.16.1"
  HELMDOCS_VERSION: "1.5.0"

jobs:
  lint:
    if: "contains(github.event.head_commit.message, 'Update chart to version')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.2.1
      - name: Lint
        run: ct lint --config .github/config/ct-lint.yaml
      - name: Lint docs
        run: .github/script/helm-docs.sh

  release:
    if: "contains(github.event.head_commit.message, 'Update chart to version')"
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3.0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
