apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}
data:
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: "true"
  SECRET_KEY_BASE: key
  SETTINGS__GITLAB_URL: {{ .Values.env.gitlabUrl | quote }}
  SETTINGS__METRICS: {{ .Values.env.metrics | quote }}
  SETTINGS__UPDATE_RETRY: {{ .Values.env.updateRetry | toString | quote }}
  SETTINGS__LOG_LEVEL: {{ .Values.env.logLevel }}
  {{- if or .Values.worker.livenessProbe.enabled .Values.worker.startupProbe.enabled }}
  SIDEKIQ_ALIVE_PORT: {{ .Values.worker.probePort | toString | quote }}
  {{- else }}
  DISABLE_SIDEKIQ_ALIVE: "true"
  {{- end }}
  {{- if .Values.env.dependabotUrl }}
  SETTINGS__DEPENDABOT_URL: {{ .Values.env.dependabotUrl | quote }}
  {{- end }}
  {{- if .Values.env.commandsPrefix }}
  SETTINGS__COMMANDS_PREFIX: {{ .Values.env.commandsPrefix | quote }}
  {{- end }}
  {{- if .Values.project_registration.mode }}
  SETTINGS__PROJECT_REGISTRATION: {{ .Values.project_registration.mode | quote }}
  {{- end -}}
  {{- if .Values.project_registration.cron }}
  SETTINGS__PROJECT_REGISTRATION_CRON: {{ .Values.project_registration.cron | quote }}
  {{- end -}}
  {{- if .Values.project_registration.namespace }}
  SETTINGS__PROJECT_REGISTRATION_NAMESPACE: {{ .Values.project_registration.namespace | quote }}
  {{- end -}}
  {{- if .Values.env.sentryDsn }}
  SENTRY_DSN: {{ .Values.env.sentryDsn | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: redis://{{ .Values.redis.fullnameOverride }}-master.{{ .Release.Namespace }}.svc.{{ .Values.redis.clusterDomain }}
  {{- else }}
  REDIS_URL: {{ required "redisUrl must be provided" .Values.env.redisUrl | quote }}
  {{- end }}
  {{- if not .Values.env.mongoDbUri }}
  MONGODB_DATABASE: {{ .Values.mongodb.auth.database }}
  MONGODB_USER: {{ .Values.mongodb.auth.username }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  MONGODB_URL: {{ .Values.mongodb.fullnameOverride }}.{{ .Release.Namespace }}.svc.{{ .Values.mongodb.clusterDomain }}:{{ .Values.mongodb.service.port }}
  {{- else if not .Values.env.mongoDbUri }}
  MONGODB_URL: {{ required "mongodbUrl must be provided" .Values.env.mongoDbUrl | quote }}
  {{- end }}
  {{- if .Values.env.http_proxy }}
  http_proxy: {{ .Values.env.http_proxy }}
  {{- end }}
  {{- if .Values.env.https_proxy }}
  https_proxy: {{ .Values.env.https_proxy }}
  {{- end }}
  {{- if .Values.env.no_proxy }}
  no_proxy: {{ .Values.env.no_proxy }}
  {{- end }}
