apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}-worker
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["sidekiq"]
          volumeMounts:
            - name: credentials
              mountPath: /home/dependabot/config/settings
          env:
            {{- include "dependabot-gitlab.database-credentials" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "dependabot-gitlab.fullname" . }}
          ports:
            - name: http
              containerPort: 7433
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.worker.probes.livenessProbe | nindent 12 }}
          startupProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.worker.probes.startupProbe | nindent 12 }}
          lifecycle:
            preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["kube/sidekiq_quiet.sh"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      terminationGracePeriodSeconds: 300 # Large dependency files or docker images can take long time to process
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "dependabot-gitlab.fullname" . }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
