apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}-worker
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      securityContext:
        {{- include "dependabot-gitlab.securityContext" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          {{- include "dependabot-gitlab.image" . | nindent 10 }}
          args: ["sidekiq"]
          volumeMounts:
            - name: credentials
              mountPath: "{{ .Values.env.appRootPath }}/{{ .Values.env.appConfigPath }}"
          env:
            {{- include "dependabot-gitlab.database-credentials" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "dependabot-gitlab.fullname" . }}
          {{- if .Values.worker.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: ["kube/sidekiq-healthcheck.sh"]
            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.worker.livenessProbe.enabled }}
          startupProbe:
            exec:
              command: ["kube/sidekiq-healthcheck.sh"]
            failureThreshold: {{ .Values.worker.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.worker.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.startupProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.worker.startupProbe.initialDelaySeconds }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ["kube/sidekiq-quiet.sh"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      terminationGracePeriodSeconds: 300 # Large dependency files or docker images can take long time to process
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "dependabot-gitlab.fullname" . }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
