apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["rails", "server"]
          volumeMounts:
            - name: credentials
              mountPath: "/home/dependabot/config/settings"
            - name: tmp
              mountPath: /home/dependabot/tmp
          env:
            {{- include "dependabot-gitlab.environment" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 120
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            failureThreshold: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["sidekiq"]
          volumeMounts:
            - name: credentials
              mountPath: /home/dependabot/config/settings
            - name: tmp
              mountPath: /home/dependabot/tmp
          env:
            {{- include "dependabot-gitlab.environment" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "dependabot-gitlab.fullname" . }}
            defaultMode: 0400
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
