apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["rails", "server"]
          volumeMounts:
            - name: credentials
              mountPath: "/home/dependabot/config/settings"
            - name: tmp
              mountPath: /home/dependabot/tmp
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: SECRET_KEY_BASE
              value: key
            - name: SETTINGS__GITLAB_URL
              value: {{ .Values.env.gitlabUrl | quote }}
            {{- if .Values.env.sentryDsn }}
            - name: SENTRY_DSN
              value: {{ .Values.env.sentryDsn }}
            {{- end }}
            {{- include "dependabot-gitlab.redisConfig" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["sidekiq"]
          volumeMounts:
            - name: credentials
              mountPath: /home/dependabot/config/settings
            - name: tmp
              mountPath: /home/dependabot/tmp
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: SECRET_KEY_BASE
              value: key
            - name: SETTINGS__GITLAB_URL
              value: {{ .Values.env.gitlabUrl | default "https://gitlab.com" | quote }}
            {{- if .Values.env.sentryDsn }}
            - name: SENTRY_DSN
              value: {{ .Values.env.sentryDsn }}
            {{- end }}
            {{- include "dependabot-gitlab.redisConfig" . | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "dependabot-gitlab.fullname" . }}
            defaultMode: 0400
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
