apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}-web
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "dependabot-gitlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "dependabot-gitlab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        {{- include "dependabot-gitlab.podAnnotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "dependabot-gitlab.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["rails", "server"]
          volumeMounts:
            - name: credentials
              mountPath: "{{ .Values.env.appRootPath }}/{{ .Values.env.appConfigPath }}"
          env:
            {{- include "dependabot-gitlab.database-credentials" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "dependabot-gitlab.fullname" . }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.web.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.web.livenessProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
            failureThreshold: {{ .Values.web.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.web.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.startupProbe.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.web.startupProbe.initialDelaySeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "dependabot-gitlab.fullname" . }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
