apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dependabot-gitlab.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
