apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dependabot-gitlab.serviceAccountName" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dependabot-gitlab.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "dependabot-gitlab.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
