apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}
type: Opaque
stringData:
  credentials.yml: |-
    production:
    {{- include "dependabot-gitlab.credentials" . | nindent 6 -}}
