apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}-registries
data:
  {{- range $key, $val := .Values.registriesCredentials }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
