apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dependabot-gitlab.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
