apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependabot-gitlab.fullname" . }}
  labels:
    {{- include "dependabot-gitlab.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: web
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.workerPort }}
      targetPort: metrics
      protocol: TCP
      name: worker
    {{- end }}
  selector:
    {{- include "dependabot-gitlab.selectorLabels" . | nindent 4 }}
